### PR TITLE
Run on Rails4

### PR DESCRIPTION
**Pull request by ykws**
NoMethodError
 undefined method
  `find_or_create_by_watchable_type_and_watchable_id_and_user_id'

### CODE REVIEW

**Comment by johnjaylward** [comment]
I just hit this error as well and applied the patch by @ykws . If this could be pulled into the main plugin code that would be great.

**Comment by ykws** [comment]
Good!

**Comment by raafael911** [comment]
@ykws Thank you for your report.
@johnjaylward If you can make a pull request I will definitely apply it to the code base.

**Comment by johnjaylward** [comment]
I just applied this pull request locally. Can you still use this one, or no since it's closed?

**Comment by ykws** [comment]
@johnjaylward I still use this one, but master merged as 3ad169740828f5da3549c5c971a2ac4daea84be2 , so I closed this pull request.

**Comment by johnjaylward** [comment]
I see, I thought it was unfixed since the PR was still open. updating to the latest worked as well.

**Pull request closed without merging**
